In [1]:
import numpy as np

In [2]:
points2d = np.array([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]])

In [3]:
points3d = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [4]:
points3d_idxs = np.array([0, 0, 1])

In [5]:
camera_idxs = np.array([0, 1, 2])

In [6]:
P = np.arange(72).reshape((6, 3, 4))

In [7]:
selected_points3d = points3d[points3d_idxs]

In [8]:
print(selected_points3d)

[[1 1 1]
 [1 1 1]
 [2 2 2]]


In [9]:
print(P)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]]


In [10]:
homo_3d_points = np.concatenate((selected_points3d, np.ones((selected_points3d.shape[0], 1))), axis=1)
homo_3d_points_T = np.transpose(homo_3d_points)

In [11]:
homo_3d_points_T

array([[1., 1., 2.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 1., 1.]])

In [12]:
calculated_points2d = np.matmul(P, homo_3d_points_T)
print(calculated_points2d)

[[[  6.   6.   9.]
  [ 22.  22.  37.]
  [ 38.  38.  65.]]

 [[ 54.  54.  93.]
  [ 70.  70. 121.]
  [ 86.  86. 149.]]

 [[102. 102. 177.]
  [118. 118. 205.]
  [134. 134. 233.]]

 [[150. 150. 261.]
  [166. 166. 289.]
  [182. 182. 317.]]

 [[198. 198. 345.]
  [214. 214. 373.]
  [230. 230. 401.]]

 [[246. 246. 429.]
  [262. 262. 457.]
  [278. 278. 485.]]]


In [13]:
calculated_points2d = calculated_points2d[camera_idxs, :, points3d_idxs]
print(calculated_points2d)
print(calculated_points2d.shape)
calculated_points2d /= calculated_points2d[:, -1].reshape((calculated_points2d.shape[0], 1))
calculated_points2d = calculated_points2d[:, :-1]

[[  6.  22.  38.]
 [ 54.  70.  86.]
 [102. 118. 134.]]
(3, 3)


In [14]:
print(calculated_points2d)

[[0.15789474 0.57894737]
 [0.62790698 0.81395349]
 [0.76119403 0.88059701]]


In [15]:
i = 3
print("calculated_points2d=", calculated_points2d[i])
print("camera_idxs[0]=", camera_idxs[i])
print("camera =", P[camera_idxs[i]])
print("points3d[0]=", points3d[points3d_idxs[i]])

print("point2d=", points2d[i])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
a = np.arange(1200).reshape((100, 3, 4))

In [ ]:
b = np.arange(400).reshape((4, 100))

In [ ]:
np.einsum('ijk,ki->ij',a,b)

In [ ]:
a

In [ ]:
b